description: |
  代码相关接口

/labor/gdp/{year}:
get:
  is: [secured]
  description: |
  劳动人口与经济关联分析预测
  queryParameters:
    year: 
      type: string
      description: |
        数据年份
  responses:
    200:
      body:
        application/json:
          schema:
            {
              "code":"200",
              "message":"成功",
              "data":{hg
                       
              },
              "success": true
               }
/labor/economic/{year}:
get:
  is: [secured]
  description: |
  劳动人口与经济指标关联度分析预测
  queryParameters:
    year: 
      type: string
      description: |
        数据年份
  responses:
    200:
      body:
        application/json:
          schema:
            {
              "code":"200",
              "message":"成功",
              "data":{
                       
              },
              "success": true
               }
/labor/industry/{year}:
get:
  is: [secured]
  description: |
  劳动人口与产业gdp比重分析预测
  queryParameters:
    year: 
      type: string
      description: |
        数据年份
  responses:
    200:
      body:
        application/json:
          schema:
            {
              "code":"200",
              "message":"成功",
              "data":{
                       
              },
              "success": true
               }               
           

